### ISSUE TITLE
Viele Requests?

### ISSUE THREAD

**Issue by Shoekrates** [c4y/tosrus#1]
Hi!
Danke für diese Erweiterung - diese Lightbox gefällt mir außerordentlich gut.
Leider erzeugt die Einbindung mehrere Requests an JS-Dateien, siehe Template:
```
<script src="system/modules/tosrus/assets/js/jquery.hammer.min.js"></script>
<script src="system/modules/tosrus/assets/js/FlameViewportScale.js"></script>
<script src="system/modules/tosrus/assets/js/jquery.tosrus.min.all.js"></script>
```
Könnte so etwas nicht noch besser zusammengefasst werden? Bzw. in den Contao-eigenen Minifizierungs- und Zusammenfassungsmechanismus integriert werden?

**Comment by c4y** [comment]
Ja. Geht natürlich. Gefixed.

**Comment by Shoekrates** [comment]
Super! Funktioniert einwandfrei. Vielen Dank!
